version: '2'
services:
    jerkk-app:
        image: jerkk
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jerkk-mysql:3306/jerkk?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://jerkk-elasticsearch:9200
        ports:
            - 8080:8080
    jerkk-mysql:
        extends:
            file: mysql.yml
            service: jerkk-mysql
    jerkk-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jerkk-elasticsearch
